language: java
jdk:
  - oraclejdk8

services:
  - postgresql

before_script:
  - psql -c 'CREATE USER "bootUser" WITH password 'bootUser' LOGIN SUPERUSER INHERIT CREATEDB CREATEROLE NOREPLICATION;' -U postgres